### ISSUE TITLE
closing the only detailed search should clear search

### ISSUE THREAD

**Issue by kwkroll32** [kwkroll32/QuaCRS#14]
When performing a detailed search, there is an "[x]" next to each element of the search. Can you modify the "[x]" button such that it fires the detailed search "Clear" button if there's only one detailed search element remaining? i.e. I want the black arrow below to behave as if the red arrow was clicked, if there was only 1 row in the detailed search dropdown. 
![issue14](https://cloud.githubusercontent.com/assets/8041208/13760087/b983db4a-ea07-11e5-8487-97d1acc67bfc.PNG)

**Comment by GeekLogan** [comment]
Fixed [here](https://github.com/kwkroll32/QuaCRS/commit/541601b2802fff0f2ef872d84597091d7dab6768)
