### ISSUE TITLE
Fstat division by zero

### ISSUE THREAD

**Issue by kwkroll32** [kwkroll32/QuaCRS#44]
![quacrs2_bug](https://cloud.githubusercontent.com/assets/8041208/13851694/769b8424-ec35-11e5-85d3-e735661b8f51.png)

**Comment by GeekLogan** [comment]
I was unable to replicate this error and it may have just been a random glitch. Nonetheless I put a catch that will make it impossible for that particular part of the program from getting a divide by zero.

**Comment by kwkroll32** [comment]
I pulled the new code and reproduced this error. I also double-checked that my f-stat calculator on cannoli has the "$fixtmp" variable, so the file really has been updated.

**Comment by GeekLogan** [comment]
Closed in latest commit
